version: '3'

services:
  basicauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  authpage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

